#!/bin/sh
# nlantau, 2021-07-04
# updated, 2021-07-23

CHLFS="/root/mount_lfs_chroot"
CRONTAB1="/var/spool/cron/crontabs/nlantau"
CRONTAB2="/var/spool/cron/crontabs/root"

PDIR="/etc/portage"
BDIR="/home/nlantau/.config/Gentoo_configs"

KERNEL="/usr/src/linux/.config"
README="/root/kernel_dev/README.md"
WORLD="/var/lib/portage/world"

PUSE="${PDIR}/package.use/local"
LF_CONF="${PDIR}/savedconfig/sys-kernel/linux-firmware"
MAKE_CONF="${PDIR}/make.conf"
LAYMAN_CONF="${PDIR}/repos.conf/layman.conf"

sudo -u nlantau /usr/bin/git --git-dir=/home/nlantau/.dotfile/ \
  --work-tree=/home/nlantau add /home/nlantau/.config/Gentoo_configs || \
  echo "Could not add Gentoo_configs too dotfiles"


{ cp ${PUSE} ${BDIR}/local.bak && \
cp ${LF_CONF} ${BDIR}/linux-firmware.bak && \
cp ${MAKE_CONF} ${BDIR}/make.conf.bak && \
cp ${LAYMAN_CONF} ${BDIR}/layman.conf.bak && \
cp ${KERNEL} ${BDIR}/`uname -r`.config && \
cp ${README} ${BDIR}/README.md && \
cp ${WORLD} ${BDIR}/world.bak && \
cp ${CHLFS} ${BDIR}/mnt_lfs && \
cp ${CRONTAB1} ${BDIR}/crontab_nlantau && \
cp ${CRONTAB2} ${BDIR}/crontab_root && \
notify-send "Gentoo config files backup completed" \
; } || notify-send "Error copying Gentoo config files"

chown -R nlantau:nlantau ${BDIR} || notify-send "Error changing owner to Gentoo config files"

date '+%X-%x' >> /home/nlantau/.config/scripts/backup_gentoo_conf.log
