#!/bin/sh

export DISPLAY=:0.0
export XAUTHORITY=/home/nlantau/.Xauthority

bat_perc=$(cat /sys/class/power_supply/BAT0/capacity)

[[ $bat_perc -le 60 ]] && notify-send "Critical battery level: $bat_perc"
