#!/bin/sh
# nlantau, 2021-04-24

M1="eDP1"
M2="DP1"
M3="DP3"


function setting_laptop {
  xrandr --output \
    $M1 --mode 1920x1080 --output \
    $M3 --off --output $M2 --off >/dev/null 2>&1
    [[ $? -eq 0 ]] || notify-send "Laptop error"

}

function setting_dual_school { 
  xrandr --output \
    $M1 --mode 1920x1080 --output \
    $M3 --mode 1920x1080 --right-of $M1 >/dev/null 2>&1
    [[ $? -eq 0 ]] || notify-send "Not Connected"
}

function setting_dual { 
  xrandr --output \
    $M1 --off --output \
    $M3 --mode 1920x1080 --output \
    $M1 --off --output \
    $M3 --mode 1920x1080 --output \
    $M2 --mode 1920x1080 --right-of $M3 >/dev/null 2>&1
}

function setting_triple {  
  # Modified to be used during labs in school
  xrandr --output \
    $M1 --mode 1920x1080 --output \
    $M3 --mode 1920x1080 --right-of \
    $M1 --output \
    $M2 --mode 1920x1080 --right-of $M3 >/dev/null 2>&1
    [[ $? -eq 0 ]] || notify-send "Not Connected"
}

function setting_dual_laptop_and_HDMI { 
  xrandr --output \
    $M1 --mode 1920x1080 --output \
    $M3 --mode 1920x1080 --same-as $M1 >/dev/null 2>&1
    [[ $? -eq 0 ]] || notify-send "Not Connected"
}

function keyrepeat_xcape {
  # key rate, replay
  xset r rate 300 50 || notify-send "xset rate error"
  xset b off || notify-send "xset bell error"

  # Screensaver off
  xset s off
  xset -dpms

  # set SE and Caps -> Ctrl
  setxkbmap se -option 'caps:ctrl_modifier' || notify-send "Setting SE error"
}



case "$1" in
  "laptop")
    setting_laptop ;
    keyrepeat_xcape ;
    ;;
  "dual")
    setting_dual ;
    keyrepeat_xcape ;
    ;;
  "triple")
    setting_triple ;
    keyrepeat_xcape ;
    ;;
  "laptop-hdmi")
    setting_dual_laptop_and_HDMI ;
    keyrepeat_xcape ;
    ;;
  *)
    notify-send "Multi Monitor Error";;
esac
