#!/bin/sh
# nlantau, 2021-07-29

# Reason: NetworkManager sometimes goes inactive

service="rc-service wpa_supplicant"

sudo $service stop #rc-service NetworkManager stop
sleep 0.5
sudo $service start #rc-service NetworkManager start
notify-send "Restarted rc-service wpa_supplicant"
